# Generated by Django 4.2.11 on 2024-04-25 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('requests', models.TextField(blank=True, null=True)),
                ('number_of_guests', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8)])),
                ('date_and_time', models.DateTimeField()),
            ],
        ),
    ]
