# Generated by Django 4.2.11 on 2024-03-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourrestaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='ourrestaurant/')),
            ],
        ),
    ]
