# Generated by Django 4.2.11 on 2024-03-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourrestaurant', '0002_chefsinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefsinfo',
            options={'verbose_name_plural': "Chef's Bio"},
        ),
        migrations.AlterModelOptions(
            name='ourrestaurant',
            options={'verbose_name_plural': 'Our Restaurant'},
        ),
    ]
