# Generated by Django 4.2.11 on 2024-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('ST', 'Starter'), ('MC', 'Main Course'), ('DS', 'Dessert'), ('DR', 'Drink')], default='MC', max_length=2),
        ),
    ]
